// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjersjdfhalvzdmoqmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuamVyc2pkZmhhbHZ6ZG1vcW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDQ2OTgsImV4cCI6MjA2MDQyMDY5OH0.zr8cShSpb9T55LC2Y40_-Mbu5FTNdHXZEJyZ1lQxDN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);